language: python
python:
    - "2.7"
env:
    - DJANGO=1.6.2
install:
    - pip install -q Django==$DJANGO
    - pip install South
    - pip install
    - easy_install --upgrade pytz
script: make test